name: Publish development to Azure

on:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.3'
    - run: composer install
    - run: git checkout -- .
    - uses: actions/setup-node@v1
    - run: npm install
    - run: php core/console --generate
    - run: npm run build
    - uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        source_dir: public
        container_name: $web
        connection_string: ${{ secrets.AzureDevConnectionString }}
