name: Trigger artifact build

on:
  push:
    branches: [ 1.x, 2.x ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
        curl -X POST https://api.github.com/repos/sleepingmonk/artifact-test/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.TEST_ARTIFACT_WORKFLOW_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": {}}'
